package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "wwccproto",
    deps = [
        ":wwproto",
    ],
)

proto_library(
    name = "wwproto",
    srcs = ["example.proto",],
)
